// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: url.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO url (url_name)
VALUES ($1)
RETURNING url_uuid
`

func (q *Queries) CreateURL(ctx context.Context, urlName interface{}) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createURL, urlName)
	var url_uuid uuid.UUID
	err := row.Scan(&url_uuid)
	return url_uuid, err
}
